import type { Post } from "./components/shared/PostCard";

export type VerificationStatus = "unverified" | "pending" | "approved" | "rejected";

export const INITIAL_POSTS: Post[] = [
  { id: "1", userId: "demo-rizky", type: "job", mode: "offline", title: "Fix leaking kitchen pipe", description: "Need a plumber to fix a leaking pipe under the kitchen sink. Materials will be provided.", budget: "Rp 250.000", category: "Repair", location: "Location shared after verification", exactLocation: "Bandung", deadline: "2026-07-20", requiredSkills: ["Plumbing", "Pipe fitting"], userName: "Rizky Pratama", authorLocation: "Bandung", verified: true, postedAt: "2h ago", createdAt: "2026-06-20T09:00:00Z", avatar: "R" },
  { id: "2", userId: "demo-ayu", type: "skill", mode: "online", title: "Logo & brand identity design", description: "I create professional logos and brand identity packages for startups and small businesses.", budget: "From Rp 300.000", category: "Design", location: "Remote", portfolioUrl: "https://example.com/ayu-designs", userName: "Ayu Setiawati", authorLocation: "Bandung", verified: true, postedAt: "4h ago", createdAt: "2026-06-20T07:00:00Z", avatar: "A", owner: true },
  { id: "3", userId: "demo-farhan", type: "job", mode: "online", title: "English to Indonesian translation", description: "Need a native translator for a 2,500 word article about technology. Deadline in 3 days.", budget: "Rp 180.000", category: "Writing", location: "Remote", userName: "Farhan Maulana", verified: false, postedAt: "6h ago", createdAt: "2026-06-20T05:00:00Z", avatar: "F" },
  { id: "4", userId: "demo-dewi", type: "skill", mode: "offline", title: "Private math tutoring (SMA level)", description: "Experienced tutor with 5 years teaching Math for high school students. Can come to your location.", budget: "Rp 80.000/hr", category: "Education", location: "Location shared after verification", exactLocation: "Jakarta Selatan", portfolioUrl: "https://example.com/dewi-tutoring", userName: "Dewi Kusuma", authorLocation: "Jakarta Selatan", verified: true, postedAt: "1d ago", createdAt: "2026-06-19T08:00:00Z", avatar: "D" },
  { id: "5", userId: "demo-budi", type: "job", mode: "online", title: "Build a landing page in React", description: "Looking for a React developer to build a clean landing page for our SaaS product. Figma design provided.", budget: "Rp 1.500.000", category: "Tech", location: "Remote", userName: "Budi Santoso", verified: false, postedAt: "1d ago", createdAt: "2026-06-19T06:00:00Z", avatar: "B" },
  { id: "6", userId: "demo-sari", type: "skill", mode: "offline", title: "House deep cleaning service", description: "Professional cleaning team for apartments and houses. 3-4 hour thorough service with eco-friendly products.", budget: "Rp 350.000", category: "Cleaning", location: "Location shared after verification", exactLocation: "Surabaya", userName: "Sari Cleaning", authorLocation: "Surabaya", verified: true, postedAt: "2d ago", createdAt: "2026-06-18T06:00:00Z", avatar: "S" },
];

